services:
  postgres:
    image: postgres:16-alpine
    container_name: traffic-postgres
    environment:
      POSTGRES_DB: traffic_violation_db
      POSTGRES_USER: traffic_admin
      POSTGRES_PASSWORD: traffic_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: traffic-redis
    ports:
      - "6379:6379"

